parameters:
    # Define the anchor with all shared Doctrine Messenger options
    doctrine_messenger_options: &doctrine_common
        table_name: messenger_messages
        auto_setup: true  # optional, can be removed if not needed

framework:

    messenger:
        failure_transport: failed

        transports:
            extract_fetch:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    <<: *doctrine_common
                    queue_name: extract_fetch

            extract_load:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    <<: *doctrine_common
                    queue_name: extract_load

            grp_extract:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    <<: *doctrine_common
                    queue_name: grp_extract

            doctrine_low:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    <<: *doctrine_common
                    queue_name: low_priority_queue


            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    delay: 2000
                    max_retries: 5
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

#            load_records:
#                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
#                options:
#                    exchange:
#                        name: load_records
#                    queues:
#                        load_records: ~
#

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_close_connection
                    - doctrine_transaction

        routing:
#            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
#            Symfony\Component\Notifier\Message\ChatMessage: async
#            Symfony\Component\Notifier\Message\SmsMessage: async
#            App\Message\ExtractMessage: load_records
            Survos\WorkflowBundle\Message\TransitionMessage: async

